Repository rishisancheti/Pathfinder-, pull requests merged in 2022-10, with the labels that each got.

#1 Djikstra Algorithm
  BFS
  Djikstra
Labels: documentation, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#2 DFS
  DFS
Labels: documentation, enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#3 TSP
  TSP
Labels: documentation, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#5 Inorder
  Inorder
Labels: documentation, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#6 Update README.md
  README.md
Labels: documentation, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#7 Update README.md
  README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#8 Update README.md
  README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#9 Update README.md
  README.md
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#11 Update README.md
  README.md
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#12 Update README.md
  README.md
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#13 Update README.md
  README.md
Labels: documentation, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#14 Update README.md
  README.md
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED
